"""add removed_at to capability entities

Revision ID: 2ae90e7010e9
Revises: 601e90b773a4
Create Date: 2026-07-16 10:46:44.512614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae90e7010e9'
down_revision: Union[str, None] = '601e90b773a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certifications', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employees', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('equipment', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('financial_records', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'removed_at')
    op.drop_column('financial_records', 'removed_at')
    op.drop_column('equipment', 'removed_at')
    op.drop_column('employees', 'removed_at')
    op.drop_column('certifications', 'removed_at')
    # ### end Alembic commands ###
