"""full schema: all tables from 05_Database_Design.md

Revision ID: 3d8622ed98f0
Revises: 265e4dc23a06
Create Date: 2026-07-15 15:52:30.828561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d8622ed98f0'
down_revision: Union[str, None] = '265e4dc23a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('documents',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_processing_status'), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRATOR', 'EXECUTIVE', 'BID_MANAGER', 'REVIEWER', 'AUDITOR', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('certifications',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('certification_name', sa.String(), nullable=False),
    sa.Column('issuing_authority', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRED', 'REVIEW_REQUIRED', name='capability_verification_status'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRED', 'REVIEW_REQUIRED', name='capability_verification_status'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('equipment_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('specifications', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRED', 'REVIEW_REQUIRED', name='capability_verification_status'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_records',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_worth', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('working_capital', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_rating', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRED', 'REVIEW_REQUIRED', name='capability_verification_status'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mission_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'AWAITING_APPROVAL', 'COMPLETED', 'ARCHIVED', name='mission_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capability_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('actual_outcome', sa.String(), nullable=True),
    sa.Column('outcome_notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capability_snapshot_id'], ['capability_snapshots.id'], name='fk_missions_capability_snapshot_id', use_alter=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name='fk_missions_recommendation_id', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('completion_status', sa.String(), nullable=True),
    sa.Column('similarity_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRED', 'REVIEW_REQUIRED', name='capability_verification_status'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_snapshots',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenders',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('tender_name', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('uploaded_document', sa.UUID(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['uploaded_document'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('GO', 'CONDITIONAL_GO', 'REVIEW', 'NO_GO', name='recommendation_type'), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('entity_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('matching_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recommendation_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['capability_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements',
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('requirement_type', sa.Enum('ELIGIBILITY', 'TECHNICAL', 'CERTIFICATION', 'EXPERIENCE', 'EVALUATION_CRITERIA', 'DEADLINE', 'SUBMISSION', name='requirement_type'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capability_mappings',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('capability_entity_type', sa.Enum('CERTIFICATION', 'EMPLOYEE', 'PROJECT', 'EQUIPMENT', 'FINANCIAL_RECORD', name='capability_entity_type'), nullable=False),
    sa.Column('capability_entity_id', sa.UUID(), nullable=False),
    sa.Column('match_status', sa.Enum('MET', 'NOT_MET', 'REVIEW_REQUIRED', 'CONDITIONAL', name='match_status'), nullable=False),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_matrix',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('MET', 'NOT_MET', 'REVIEW_REQUIRED', 'CONDITIONAL', name='match_status'), nullable=False),
    sa.Column('supporting_evidence', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('verification_reason', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED_COMPLIANT', 'VERIFIED_NON_COMPLIANT', 'ESCALATED', name='compliance_matrix_verification_status'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matching_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evidence_reference', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # These two constraints are circular (missions <-> capability_snapshots,
    # missions <-> recommendations) and were deliberately excluded from
    # 'missions' at creation time via use_alter=True. Alembic's autogenerate
    # does not automatically emit the follow-up ALTER TABLE for use_alter
    # constraints, so they're added explicitly here, now that both sides
    # of each relationship exist.
    op.create_foreign_key(
        'fk_missions_capability_snapshot_id', 'missions', 'capability_snapshots',
        ['capability_snapshot_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_missions_recommendation_id', 'missions', 'recommendations',
        ['recommendation_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the deferred FKs first — they must go before 'missions' is dropped
    # and before the tables they point to are dropped.
    op.drop_constraint('fk_missions_recommendation_id', 'missions', type_='foreignkey')
    op.drop_constraint('fk_missions_capability_snapshot_id', 'missions', type_='foreignkey')

    op.drop_table('compliance_matrix')
    op.drop_table('capability_mappings')
    op.drop_table('requirements')
    op.drop_table('recommendations')
    op.drop_table('tenders')
    op.drop_table('capability_snapshots')
    op.drop_table('audit_logs')
    op.drop_table('projects')
    op.drop_table('missions')
    op.drop_table('financial_records')
    op.drop_table('equipment')
    op.drop_table('employees')
    op.drop_table('certifications')
    op.drop_table('users')
    op.drop_table('documents')
    op.drop_table('companies')
    # ### end Alembic commands ###
