"""add uploaded_by to documents

Revision ID: 601e90b773a4
Revises: 3d8622ed98f0
Create Date: 2026-07-16 02:02:14.792912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601e90b773a4'
down_revision: Union[str, None] = '3d8622ed98f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'uploaded_by')
    # ### end Alembic commands ###
