"""add indexes to frequently-filtered foreign key columns (RC-1 audit finding B3)

Postgres does not automatically index foreign-key columns (only primary
keys and unique constraints get one for free). company_id, mission_id,
tender_id, requirement_id, and recommendation_id are filtered on
constantly across every service in this codebase -- this was invisible
at pilot scale but would become a real cost (sequential scans) as real
usage accumulates. Hand-written rather than autogenerated (no live
Postgres instance was available in the environment this was written in),
following the exact naming/shape Alembic's own autogenerate produces for
a plain index=True column (ix_<table>_<column>, non-unique).

Revision ID: 8f1a2c9d4b6e
Revises: 2ae90e7010e9
Create Date: 2026-07-24 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f1a2c9d4b6e'
down_revision: Union[str, None] = '2ae90e7010e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (index_name, table_name, column_name) — matches app/models/*.py's index=True additions exactly.
_INDEXES = [
    ("ix_certifications_company_id", "certifications", "company_id"),
    ("ix_employees_company_id", "employees", "company_id"),
    ("ix_projects_company_id", "projects", "company_id"),
    ("ix_equipment_company_id", "equipment", "company_id"),
    ("ix_financial_records_company_id", "financial_records", "company_id"),
    ("ix_documents_company_id", "documents", "company_id"),
    ("ix_missions_company_id", "missions", "company_id"),
    ("ix_capability_snapshots_mission_id", "capability_snapshots", "mission_id"),
    ("ix_users_company_id", "users", "company_id"),
    ("ix_tenders_mission_id", "tenders", "mission_id"),
    ("ix_requirements_tender_id", "requirements", "tender_id"),
    ("ix_capability_mappings_requirement_id", "capability_mappings", "requirement_id"),
    ("ix_capability_mappings_capability_entity_id", "capability_mappings", "capability_entity_id"),
    ("ix_recommendations_mission_id", "recommendations", "mission_id"),
    ("ix_compliance_matrix_recommendation_id", "compliance_matrix", "recommendation_id"),
    ("ix_compliance_matrix_requirement_id", "compliance_matrix", "requirement_id"),
    ("ix_audit_logs_mission_id", "audit_logs", "mission_id"),
]


def upgrade() -> None:
    for index_name, table_name, column_name in _INDEXES:
        op.create_index(op.f(index_name), table_name, [column_name], unique=False)


def downgrade() -> None:
    for index_name, table_name, column_name in reversed(_INDEXES):
        op.drop_index(op.f(index_name), table_name=table_name)
