"""add removed_at to documents

Revision ID: 9c1f4b7a2e3d
Revises: 8f1a2c9d4b6e
Create Date: 2026-07-25 11:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1f4b7a2e3d'
down_revision: Union[str, None] = '8f1a2c9d4b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'removed_at')
    # ### end Alembic commands ###
