import { jsPDF } from "jspdf";
import type { EvaluationResponse } from "../api/types";
import { recommendationLabel } from "./recommendationLabels";

interface MergedRow {
  id: string;
  status: string;
  heading: string;
  mandatory: boolean | null;
  risk_level: string | null;
  matching_confidence: number | null;
}

interface ReportMeta {
  companyName: string;
  missionType: string;
  missionId: string;
}

const BRAND_PRIMARY: [number, number, number] = [99, 102, 241]; // #6366F1
const INK: [number, number, number] = [30, 32, 44];
const MUTED: [number, number, number] = [100, 116, 139]; // Dark Slate #64748B

const PAGE_WIDTH = 210;
const MARGIN = 18;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const PAGE_HEIGHT = 297;
const FOOTER_Y = PAGE_HEIGHT - 12;

function pct(v: number | null) {
  return v == null ? "—" : `${Math.round(v * 100)}%`;
}

/**
 * Generates a real, professional PDF client-side (jsPDF) from data already
 * on the page -- no backend endpoint required. Replaces the earlier plain
 * .txt export.
 */
export function generateEvaluationPdf(data: EvaluationResponse, merged: MergedRow[], meta: ReportMeta) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = 0;

  const addFooter = () => {
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setDrawColor(...MUTED);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, FOOTER_Y - 4, PAGE_WIDTH - MARGIN, FOOTER_Y - 4);
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text("Generated by BidOps AI — From Documents to Decisions.", MARGIN, FOOTER_Y);
      doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, FOOTER_Y, { align: "right" });
    }
  };

  const ensureSpace = (needed: number) => {
    if (y + needed > FOOTER_Y - 10) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const heading = (text: string) => {
    ensureSpace(12);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...INK);
    doc.text(text, MARGIN, y);
    y += 2;
    doc.setDrawColor(...BRAND_PRIMARY);
    doc.setLineWidth(0.6);
    doc.line(MARGIN, y, MARGIN + 14, y);
    y += 7;
  };

  // --- Header band ---
  doc.setFillColor(...BRAND_PRIMARY);
  doc.rect(0, 0, PAGE_WIDTH, 32, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("BidOps AI", MARGIN, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Tender Analysis Report", MARGIN, 20.5);
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.text("From Documents to Decisions.", MARGIN, 27);
  y = 42;

  // --- Executive summary meta table ---
  const { recommendation, gap_analysis } = data;
  const metaRows: [string, string][] = [
    ["Company", meta.companyName || "—"],
    ["Mission", meta.missionType],
    ["Date", new Date(recommendation.generated_at).toLocaleString()],
    ["AI Decision", recommendationLabel(recommendation.recommendation_type)],
    ["Risk Level", recommendation.risk_level ? recommendation.risk_level.toUpperCase() : "—"],
    ["Overall Confidence", pct(recommendation.overall_confidence)],
  ];

  doc.setFontSize(10);
  metaRows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...MUTED);
    doc.text(`${label}:`, MARGIN, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...INK);
    doc.text(value, MARGIN + 42, y);
    y += 6;
  });
  y += 4;

  // --- Executive summary paragraph ---
  heading("Executive Summary");
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...INK);
  const summaryLines = doc.splitTextToSize(recommendation.executive_summary ?? "No summary available.", CONTENT_WIDTH);
  ensureSpace(summaryLines.length * 5 + 4);
  doc.text(summaryLines, MARGIN, y);
  y += summaryLines.length * 5 + 8;

  // --- Confidence breakdown ---
  heading("Confidence Breakdown");
  const confRows: [string, string][] = [
    ["Document Confidence", pct(recommendation.document_confidence)],
    ["Entity Confidence", pct(recommendation.entity_confidence)],
    ["Matching Confidence", pct(recommendation.matching_confidence)],
    ["Recommendation Confidence", pct(recommendation.recommendation_confidence)],
  ];
  doc.setFontSize(10);
  confRows.forEach(([label, value]) => {
    ensureSpace(6);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(label, MARGIN, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...INK);
    doc.text(value, MARGIN + 60, y);
    y += 6;
  });
  y += 4;

  // --- Risk / gap analysis (mandatory blockers first) ---
  const blocking = gap_analysis.filter((g) => g.mandatory && g.status === "not_met");
  heading(`Risk Assessment — ${blocking.length} Mandatory Gap(s)`);
  if (blocking.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...INK);
    doc.text("No mandatory requirements are unmet.", MARGIN, y);
    y += 8;
  } else {
    blocking.forEach((g, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${g.description ?? "Requirement"}`, CONTENT_WIDTH);
      ensureSpace(lines.length * 5 + 4);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...INK);
      doc.text(lines, MARGIN, y);
      y += lines.length * 5 + 1;
      if (g.reason) {
        const reasonLines = doc.splitTextToSize(g.reason, CONTENT_WIDTH - 4);
        ensureSpace(reasonLines.length * 4.5 + 3);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...MUTED);
        doc.text(reasonLines, MARGIN + 4, y);
        y += reasonLines.length * 4.5 + 3;
      }
    });
    y += 4;
  }

  // --- Compliance matrix ---
  heading(`Compliance Matrix — ${merged.length} Requirement(s)`);
  doc.setFontSize(9);
  merged.forEach((row, i) => {
    const statusLabel = `[${row.status.toUpperCase().replace(/_/g, " ")}]`;
    const lines = doc.splitTextToSize(`${i + 1}. ${statusLabel} ${row.heading}`, CONTENT_WIDTH);
    ensureSpace(lines.length * 4.6 + 2);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...INK);
    doc.text(lines, MARGIN, y);
    y += lines.length * 4.6 + 2;
  });

  addFooter();
  doc.save(`bidops-report-${meta.missionId.slice(0, 8)}.pdf`);
}
